import { redirect } from "next/navigation";
import { cookies } from "next/headers";
import Providers from "@/redux/Providers";
import { Toaster } from "react-hot-toast"
import "../styles/taiwind.css";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const cookieStore = cookies();
  const token = cookieStore.get("token");
  if (token) {
    redirect("/auth/login");
  }
  return (
    <html lang="en" >
      <body className="overflow-x-hidden"  suppressHydrationWarning={true}>
        <Providers>{children}
        <Toaster />
        </Providers>
      </body>
    </html>
  );
}
